# OPC UA connection settings
[opcua]
url = "opc.tcp://192.168.1.43:49320/KEPServerEX"
user = ""
pass = ""

# MQTT connection settings
[mqtt]
host = "localhost"
port = 1883
username = ""
password = ""

# Metrics to collect
[[metrics]]
datatype = "number"
tags = { machine = "machine_1", fields = "valid_job" }
nodeId = "ns=2;s=Painting.MachineID.Valid_job"
interval = 1000
topic = "painting/machineID/valid_job"
mode = "pub"  
# Options: pub, sub, pubsub

[[metrics]]
datatype = "number"
tags = { machine = "machine_2", fields = "invalid_job" }
nodeId = "ns=2;s=Painting.MachineID.Invalid_job"
interval = 1000
topic = "painting/machineID/invalid_job"
mode = "pubsub"  
# Options: pub, sub, pubsub

